### ISSUE TITLE
Multinomial should return Int64 instead of Float

### ISSUE THREAD

**Issue by marcelluethi** [sbrunk/storch#54]
I ran into a problem while using `torch.multinomial`. 
When taking the resulting tensor, converting it to a `Seq` and mapping over the elements, I get the following error:
```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Float (java.lang.Long and java.lang.Float are in module java.base of loader 'bootstrap')
```

The problem is that pytorch returns a `long`,  but the return type of storch is `Tensor[D]` (where `D <: FloatNN`):
```
  def multinomial[D <: FloatNN](
      input: Tensor[D],
      numSamples: Long,
      replacement: Boolean = false,
  ): Tensor[D] =
```

The following change fixes the problem for me:
```
  def multinomial[D <: FloatNN](
      input: Tensor[D],
      numSamples: Long,
      replacement: Boolean = false
  ): Tensor[Int64] =
    Tensor(torchNative.multinomial(input.native, numSamples, replacement), dtype=int64)
```

As there are multiple TODOs in the code, some of which I don't understand clearly enough, I did not start a PR. Let me know if you would like me to make a PR with this change. 

ps. It would also be nice if multinomial would take a generator as an argument.

**Comment by sbrunk** [comment]
Yes the torch docs also say it returns a `LongTensor`: https://pytorch.org/docs/stable/generated/torch.multinomial.html#torch.multinomial

Fixed via #55 

Greetings from Madrid, where Scala Days has just ended. I've given my Storch talk and had lot's of interesting conversations about it. Need to recover now.
