### ISSUE TITLE
Importing Storch release 

### ISSUE THREAD

**Issue by davidedomini** [sbrunk/storch#66]
Hello,

I was trying to import Storch from the OSS Sonatype Snapshot Repository as indicated in your [documentation](https://storch.dev/installation.html).

Everything works fine when using SBT, but theoretically, it should also work with Gradle (properly configured). However, when attempting to import it with Gradle, the following error is encountered: 
```bash
storch-example:main: Could not find dev.storch:core:0.0-05078a8-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/dev/storch/core/0.0-05078a8-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/dev/storch/core/0.0-05078a8-SNAPSHOT/core-0.0-05078a8-SNAPSHOT.pom
  - https://oss.sonatype.org/content/repositories/snapshots/dev/storch/core/0.0-05078a8-SNAPSHOT/maven-metadata.xml
  - https://oss.sonatype.org/content/repositories/snapshots/dev/storch/core/0.0-05078a8-SNAPSHOT/core-0.0-05078a8-SNAPSHOT.pom
```

[Here you can find a minimal reproducible example](https://github.com/davidedomini/storch-example)

I've tried to investigate this error, and I found some strange things:

1. Using a custom SBT task, I printed the link to the repository that the code ``Resolver.sonatypeOssRepos("snapshots")``  points to, and obtained the following link: https://oss.sonatype.org/content/repositories/snapshots . However, if you access the [repository](https://oss.sonatype.org/content/repositories/snapshots/dev/) from a browser and try to navigate it, Storch cannot be found.

2. If you try to import another software (e.g., ``"dev.jeka:kotlin-plugin:master-SNAPSHOT"``) published on the same repository from Gradle, everything works fine (indicating that the Gradle build is configured correctly).

**Comment by sbrunk** [comment]
Storch is published to the "new" snapshots repo s01: https://s01.oss.sonatype.org/#nexus-search;gav~dev.storch

The SBT Resolver picks up both. if you configure `Resolver.sonatypeOssRepos("snapshots")`, but I guess you have to do it manually in gradle (see also the scala-cli tab).

Since you've already closed it, did you figure it out already? If you have a working gradle build, I'd be happy to add an example to the docs for the next person running into this.

**Comment by davidedomini** [comment]
Hi Sören,
Here it is: https://github.com/davidedomini/storch-example

**Comment by davidedomini** [comment]
N.B. regarding org.bytedeco.cuda 

Importing with the version indicated in storch documentation doesn't work
